In [ ]:
!pip install -U peft bitsandbytes transformers accelerate

Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.2.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft) (4.67.3)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.7.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.4.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (3.24.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft) (1.3.4)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (0.24.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (0.1.2)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 13.9 MB/s eta 0:00:00
Downloading transformers-5.2.0-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 123.9 MB/s eta 0:00:00
Installing collected packages: bitsandbytes, transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed bitsandbytes-0.49.2 transformers-5.2.0

In [ ]:
!pip install -U trl

Collecting trl
  Downloading trl-0.28.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.12.0)
Requirement already satisfied: datasets>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from trl) (4.0.0)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.0)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.2.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.4.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (3.24.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (2025.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.24.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2026.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers>=4.56.2->trl) (0.24.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.0.0->trl) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers>=4.56.2->trl) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers>=4.56.2->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers>=4.56.2->trl) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate>=1.4.0->trl) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers>=4.56.2->trl) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers>=4.56.2->trl) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers>=4.56.2->trl) (0.1.2)
Downloading trl-0.28.0-py3-none-any.whl (540 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 540.5/540.5 kB 11.8 MB/s eta 0:00:00
Installing collected packages: trl
Successfully installed trl-0.28.0

In [ ]:
from datasets import Dataset, load_dataset
dataset = load_dataset("JAYASREESS/semantic_integrity", split="train")

In [ ]:
!pip install PyMuPDF

Requirement already satisfied: PyMuPDF in /usr/local/lib/python3.12/dist-packages (1.27.1)

In [ ]:
print(dataset)

Dataset({
    features: ['pdf'],
    num_rows: 4
})

In [ ]:
# Removed: This installation caused a conflict with PyMuPDF
# pip install fitz

In [ ]:
!pip install pdfplumber

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.9)
Requirement already satisfied: pdfminer.six==20251230 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.5.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)

In [ ]:
!pip uninstall -y fitz PyMuPDF
!pip install -U PyMuPDF

Found existing installation: fitz 0.0.1.dev2
Uninstalling fitz-0.0.1.dev2:
  Successfully uninstalled fitz-0.0.1.dev2
WARNING: Skipping PyMuPDF as it is not installed.
Collecting PyMuPDF
  Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.27.1-cp310-abi3-manylinux_2_28_x86_64.whl (24.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 60.2 MB/s eta 0:00:00
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.27.1

In [ ]:
import fitz
def extract_text_from_pdf(pdf_path):
    text_blocks = []
    with fitz.open(pdf_path) as doc:
        for page in doc:
            text = page.get_text("text").strip()
            if text:
                text_blocks.append(text)
    return text_blocks

In [ ]:
pdf_files = [
    "/content/dox1.pdf",
    "/content/dox 2-1.pdf",
    "/content/dox 3-1.pdf",
    "/content/dox 4-1.pdf"
]

pdf_texts = []
for pdf_file in pdf_files:
    extracted_blocks = extract_text_from_pdf(pdf_file)
    pdf_texts.extend(extracted_blocks)

In [ ]:


pdf_texts

["Clean Sale Deed \n \n09.02.2026 (Two thousand twenty-sixth year, February month, ninth day) Krishnagiri \nDistrict, Thenkanikottai Taluk. Thottathimmanahalli Post, Veppalampatti village, residing \nat door number 3/69, Late Govindan's son Sakthivel  to you. \n \nKrishnagiri District, Thenkanikottai Taluk, Thottathimmanahalli Post, Veppalampatti \nvillage, residing at door number 3/65, Chinnakannu's wife Rathinammal.1 , the above-\nmentioned 1st party Rathinammal & Chinnakannu's daughter, and Saakkappan's wife \nSanthi. \n. \nThe \nabove-mentioned \nKrishnagiri \nDistrict, \nThenkanikottai \nTaluk, \nThottathimmanahalli Post, Veppalampatti village, residing at door number 3/65, \nNakappan (alias Chinnasaakkappan)'s son Kannan (alias Kannappan). 3 , the above-\nmentioned Krishnagiri District, Thenkanikottai Taluk, Thottathimmanahalli Post, \nVeppalampatti village, residing at door number 3/65, Kannan (alias Kannappan)'s son \nLate Govindan's wife Roja.4  , the above-mentioned 4th party Roja & Late Govindan's son \nSathya.5, Sandhya. all of us have mutually agreed and written this clean sale deed, which \nmeans \n \nEven now, for us, the husband of the person listed as number 1 and the father of the \nperson listed as number 2, Mr. Chinnakannan, and for us, the person listed as number 3, \nKannan (alias Kannappan), based on U.D.R. joint patta number 907, the land measured \nas Nellur village survey number 7/5A - area 0.45.0 hectares, exactly corresponding to 1.12 \nacres (one acre and twelve cents), the land with a common half share of 0.56 acres (fifty-\nsix cents) allotted to the said Chinnakannan, was settled in the name of the person listed \nas number 1 on 24.04.1989 at the Rayakottai Sub-Registrar Office as document number \n335/1989 through a gift settlement deed. Further, based on the said gift settlement deed \nand from Deepika, the daughter of the person listed as number 1 and sister of the person \nlisted as number 2, on 04.05.2021, a release deed was obtained in the names of the \npersons listed as numbers 1 and 2. Based on this, the land measuring 1.12 acres (one acre \nand twelve cents) corresponding exactly to Nellur village survey number 7/5A - area \n0.45.0 hectares, and the common half share of 0.56 acres (fifty-six cents) allotted to the \nperson listed as number 3, Kannan (alias Kannappan), under U.D.R. joint patta number \n907, was also allotted as a joint patta holder to the person listed as number 3, and was \ninherited by the persons listed as numbers 4 to 6. \n \nBased on our joint independent experience, we have identified and agreed to purchase \nthe entire land of Nellore village survey number 7/5A - area 0.45 hectares, equivalent to \n1.12 acres (one acre and twelve cents), without any prior encumbrances, for our family \nexpenses and to settle retail debts, for the amount of Rs. 5,50,000/- (Five lakh fifty \nthousand rupees). \n \nThe above purchase amount of Rs. 5,50,000/- (Five lakh fifty thousand rupees) has been \nreceived by us from you today as bank funds in the presence of the witnesses below, and \nwe \nhave \ntoday \nmade \nthe \nsaid \nproperty \nyour \nabsolute \nownership.",
 'From tomorrow onwards, you shall get the title deed for the above purchased property \ntransferred in your name, pay the necessary taxes and other dues, and enjoy the property \nwith full freedom and perpetuity, along with all transactions such as purchase, gift, and \ninheritance by your sons, grandsons, and descendants as per your wish. Further, neither \nwe nor any of our minor or major heirs shall have any share, freedom, or right whatsoever \nin the above property, and we have not created any encumbrance or dependency on the \nsaid property. If there is any encumbrance or any civil or criminal case known to exist, we \nourselves will resolve it at our own expense. Our sincere and agreed purchase deed has \nbeen written and signed accordingly. \n \nThe above-mentioned purchased property falls under Kelamangalam Union, \nThottathimmanahall Panchayat jurisdiction. \n \n \n \n \n \n                                 Details of the purchased property \n \nKrishnagiri Reedy, Rayakottai Sub Reedy, Krishnagiri District. Thenkanikkottai Taluk, \nNellur Village Survey No. 7/5A (Seven / Five A) land. Hectares 0.45.5 with a value of Rs. \n1.25 per unit. This corresponds to land measuring 1.12 acres (One acre twelve cents) \nfully owned (according to document numbers 335/1989 & 1205/2021, land measuring \n0.56 acres cents, and according to Patta No. 907, land measuring 0.56 acres cents) along \nwith the customary pathway leading to the above land, including the above-mentioned \nroad, is subject to clear purchase. \n \nThe current market value of the above-purchased property is Rs. 5,61,120/-. \n \nWitnesses: \n \n1. (Sakkappan) Th/P Muniyappan. Ullatti Village . \n \n2. (Senthaayappan) Th/Pe Rajappan, Ullatti Village .',
 "Sale Agreement Document \nSale Amount Rs. 1,20,000/- \nAdvance Payment Rs. 20,000/- \nGrace Period 2 years \nOn 13.02.2026 (the year two thousand twenty-six, February month, \nthirteenth day) in Krishnagiri district, Sulagiri taluk, Uthanapalli post. \nVenkatesapuram village. Door number 1/1116, residing Ayyappa's son \nAshok. \nIn Krishnagiri district, Sulagiri taluk, Uthanapalli post, Devasanapalli village, \ndoor number 1302A, residing Chinnadurai's son C. Arivazhagan. the two of \nus have mutually agreed and written this sale agreement document as \nfollows: \nEven now, two of us have independently purchased the property described \nunder document number 3095/2021 at the Rayakottai Sub-Registrar's \nOffice, based on the individual freehold experience of two persons. Out of \nthis, one of us has agreed to buy the detailed property for Rs. 1,20,000/- (One \nlakh twenty thousand rupees). Out of the above purchase amount, an \nadvance of Rs. 20,000/- (Twenty thousand rupees) has been paid by one \nperson to the other two persons, who have received the cash and signed the \nagreement document. The remaining balance purchase amount of Rs. \n1,00,000/- (One lakh rupees) shall be paid by one person to the other two \npersons within 2 (two) years from today, and the purchase registration must \nbe done in the name of either the one person or the person requested by him \nby the two persons. If, within the said period, the balance purchase amount \nis paid by one person to the other two persons and the purchase registration \nis done, even if the two persons demand a higher purchase amount or delay \nthe registration citing excuses, one person has the right to file this agreement \ndocument and the balance amount in the relevant court without expecting \ncooperation from the two persons. The two persons have no right to object \nto the compulsory registration by one person or to the freehold of the \nproperty by one person. Our consent has been given and the purchase",
 'agreement document has been signed accordingly. The above property has \nnot been given freehold yet. \n                                            Property  Details \n \nKrishnagiri Reedy. Rayakottai Sabreedy. Krishnagiri District. Sulagiri Taluk. \nUthanapalli Village Survey No. 682/2 (Six hundred eighty-two / two) land, \nHect. 0.14.0 with a value of Rs. 0.45. Within this, new subdivision Survey \nNo. 682/2B2 (Six hundred eighty-two / two B two) land Hect. 0.01.20 with a \nvalue of Rs. 0.10. Patta No. 3098. Details of boundaries are as follows: \nEast- Survey No. 683 land \nWest - Land left for pathway \nNorth - Manjula. Venkatesh land \nSouth - Survey No. 679/1 Arivazhagan land, Survey No.          \n682/3 land & Panchayat road \nIn the middle of this, there is a land measuring exactly Hect. 0.03 (three \ncents) with a well and also \nThe above Uthanappalli village survey number 679/1 (six hundred seventy-\nnine / one) land area 0.01 hectares has a resolution of Rs.0.06, Patta \nnumber 3098. Correspondingly, land with an area of 0.02% hectares (two \nand a half cents) including the pond and combined in the above two survey \nnumbers, land with an area of 0.05½ hectares (five and a half cents) \nincluding the usual pathway leading to the above lands is subject to the \nabove road purchase agreement document. \n \nThe current market value of the above properties is Rs.1,20,000/- \n \nWitnesses: \n \n1. (Murugesh) Th/P Muniyappa, Uthanappalli village. \n2. (Santhamma) K/Pe Rajendran. Thuppukanappalli village.',
 "Clean Sale Deed \n13.02.2026 (Two thousand twenty-sixth year. February month. Thirteenth day) \nDharmapuri District, Pappirettipatti Taluk. Pommidi Post. Pommidi. B-Dhruñchipatti. \nBoyar Street Door No. 3/222, residing Raja's wife Jayamani to you \nKarnataka State, Bengaluru District. Anekal Taluk. Anekal Thali Road, Thikala \nStreet, Ward No. 2, residing Ledramakrishnappa's son Ramesh  I have willingly written \nand given this clean sale deed which means \nEven now, at the Rayakottai Sub-Registrar Office, document No. 5169/2025, as a \nD-Schedule document, based on which I have been in free possession until yesterday, \nthe property detailed therein without any prior encumbrance, for my family expenses and \nagricultural expenses, I have agreed to sell to you for Rs. 1,00,000/- (One lakh two \nhundred) rupees, and the above sale amount Rs. 100,200/- (Two lakh two hundred) \nrupees I have received from you today in the presence of the following witnesses and I \nhave today made the below property your freehold. \nFrom now on, on tomorrow's date itself, you shall transfer the title deed of the \nabove-mentioned purchased property into your name. You shall pay all the necessary \ntaxes and other charges and enjoy the property freely and eternally, along with all the \nrights of inheritance through your sons, grandsons, and lineage, with full freedom and \nas per your wish, including all transactions like gifts and transfers. Henceforth, neither I \nnor any of my minor or major heirs shall have any right, claim, or freedom over the said \nproperty, and I have not created any kind of encumbrance or dependence on the said \nproperty. If there are any encumbrances or any civil or criminal cases related to this, I \nwill resolve them at my own expense. If any cases are hidden and documents are \nregistered, I agree to abide by the decisions taken by the honorable court in this regard. I \nhereby confirm this, and I have willingly signed and executed this clean sale deed. \n \n           The above-mentioned purchased property falls under the jurisdiction of Sulagiri \nUnion, Thuppukanapalli Panchayat.",
 'Sale Property Details \n \n        Krishnagiri Reddy. Rayakottai Sub Reddy. Krishnagiri District. Sulagiri Taluk. \nThuppukanappalli Village Survey No. 295 (Two hundred ninety-five) Land, Hectare \n0.98.5 with a price of Rs. 0.61. In this, new subdivision Survey No. 295/2 (Two hundred \nninety-five / two) Land Hectare 0.24,64 with a price of Rs. 0.15. Details of boundaries: \n                                      East - Survey No. 295/3 Land \n                                      West - Muthuraj Land \n                                      North - Remaining land in the same survey number \n                                      South - Survey No. 296 Adjacent land \nIn the middle of this, land of 0.20 acres (twenty cents) with a path leading to the above \nland including a common pathway is included in the clear sale. \n \nThe current market value of the above sale property is Rs. 1,00,200/-. \n \nWitnesses: \n \n1. (Senthilkumar) S/o Chinnappa, Utthanappalli Village. \n \n2. (Venkatesh) S/o Gopalappa, Chinnalakshmipuram Village.',
 "Clean Purchase Deed \n \n26.09.2025 (September, twenty-sixth, year two thousand and twenty-five) To you, N. Durai \nNagaraj, son of Nagaraj, residing at Door No. 4/155, Village Koothandahalli, Nammanthahalli \nPost Office, Palacode Taluk, Dharmapuri District \n \nThe following is the pure purchase deed written by us, Late Thottayan's wife \nMuniyammal.1residing at Door No. 5/227, Thottatimmanahalli Post Office, Palakodu Taluk, \nDharmapuri District, and the sons of the above 1 lakh Muniyammal & Late Thottayan, \nSakthivel, Bhagyaraj. , Ajithkumar. \n \nNow, the deceased Thottayan, who is the husband of 1 lakh people among us and the father \nof 2 to 4 lakh people, has obtained the property in the Rayakottai Registrar's Office as \nDocument No. 2296/2015 as the basis of the purchase document. After the death of the said \nThottayan (15.05.2021), the inheritance certificate No. was obtained by the Palakodu \nVatachiyar. As per TN-720210612721, we, the heirs of the 1st to 4th lakhs, have been allotted \nthe property mentioned herein, which has been acquired by us from our joint ownership \nexperience till date, without any prior reservation, for our family expenses and agricultural \nexpenses, at a cost of Rs. 1,79,000/- (one lakh seventy nine thousand) rupees, and the above \ncost amount is Rs. 1,79,000/- (one lakh seventy nine thousand) We have received from you \ntoday in the presence of the following witnesses the sum of Rs. 1913155000028662 through \nCheque No. 000003 drawn from Karur Vysya Bank, Rayakottai Branch Savings Account No. \n1913155000028662 and have also taken possession of the following properties today. \n \nFrom now on, you shall transfer the title deed for the above properties to your name, pay the \ndues, taxes, etc., and enjoy them in perpetuity with complete freedom and with all \ntransactions as you wish, including purchases, donations, etc., as per your will. \nFurthermore, we and our minor or major heirs have no right, title or interest in the above \nproperties, and we have not committed any encroachment on the above properties, and we \nwill settle any such encroachment, civil or criminal cases, if any, at our own expense. This is \na clean purchase deed that we have written down in our minds.The above purchase \nproperties are within the limits of Palacode Union, Kummanur Panchayat.",
 'Purchase Property Details \nKrishnagiri Reedy, Rayakottai Sub-Reedy, Dharmapuri District, Palacode Taluk, \nChinnegaundanahalli Village Survey No. 87/1A (Eighty Seven / One A) Land 1.41.5 with a tax \nof Rs. 3.92, out of which new subdivision Survey No. 87/1A1 (Eighty Seven / One A) Land \n1.27.75 with a tax of Rs. 3.54, out of which the cross-section details are \nEast - Krishnan Land \nWest - Suresh Land \nNorth - Suresh Land \nSouth - Thottayan Land \nIn the middle of this, a land measuring 0.38 (thirty-eight cents) and']

In [ ]:
import re
def split_paragraphs(pages):
    paragraphs = []
    for page_text in pages:
        # Split on double line breaks or long newlines
        chunks = re.split(r'\n\s*\n', page_text)
        for chunk in chunks:
            clean = chunk.strip()
            if len(clean) > 30:  # ignore too short lines
                paragraphs.append(clean)
    return paragraphs

In [ ]:
paragraphs = split_paragraphs(pdf_texts)

In [ ]:
data = [{"text": p} for p in paragraphs]

In [ ]:
print(data)

[{'text': "09.02.2026 (Two thousand twenty-sixth year, February month, ninth day) Krishnagiri \nDistrict, Thenkanikottai Taluk. Thottathimmanahalli Post, Veppalampatti village, residing \nat door number 3/69, Late Govindan's son Sakthivel  to you."}, {'text': "Krishnagiri District, Thenkanikottai Taluk, Thottathimmanahalli Post, Veppalampatti \nvillage, residing at door number 3/65, Chinnakannu's wife Rathinammal.1 , the above-\nmentioned 1st party Rathinammal & Chinnakannu's daughter, and Saakkappan's wife \nSanthi. \n. \nThe \nabove-mentioned \nKrishnagiri \nDistrict, \nThenkanikottai \nTaluk, \nThottathimmanahalli Post, Veppalampatti village, residing at door number 3/65, \nNakappan (alias Chinnasaakkappan)'s son Kannan (alias Kannappan). 3 , the above-\nmentioned Krishnagiri District, Thenkanikottai Taluk, Thottathimmanahalli Post, \nVeppalampatti village, residing at door number 3/65, Kannan (alias Kannappan)'s son \nLate Govindan's wife Roja.4  , the above-mentioned 4th party Roja & Late Govindan's son \nSathya.5, Sandhya. all of us have mutually agreed and written this clean sale deed, which \nmeans"}, {'text': 'Even now, for us, the husband of the person listed as number 1 and the father of the \nperson listed as number 2, Mr. Chinnakannan, and for us, the person listed as number 3, \nKannan (alias Kannappan), based on U.D.R. joint patta number 907, the land measured \nas Nellur village survey number 7/5A - area 0.45.0 hectares, exactly corresponding to 1.12 \nacres (one acre and twelve cents), the land with a common half share of 0.56 acres (fifty-\nsix cents) allotted to the said Chinnakannan, was settled in the name of the person listed \nas number 1 on 24.04.1989 at the Rayakottai Sub-Registrar Office as document number \n335/1989 through a gift settlement deed. Further, based on the said gift settlement deed \nand from Deepika, the daughter of the person listed as number 1 and sister of the person \nlisted as number 2, on 04.05.2021, a release deed was obtained in the names of the \npersons listed as numbers 1 and 2. Based on this, the land measuring 1.12 acres (one acre \nand twelve cents) corresponding exactly to Nellur village survey number 7/5A - area \n0.45.0 hectares, and the common half share of 0.56 acres (fifty-six cents) allotted to the \nperson listed as number 3, Kannan (alias Kannappan), under U.D.R. joint patta number \n907, was also allotted as a joint patta holder to the person listed as number 3, and was \ninherited by the persons listed as numbers 4 to 6.'}, {'text': 'Based on our joint independent experience, we have identified and agreed to purchase \nthe entire land of Nellore village survey number 7/5A - area 0.45 hectares, equivalent to \n1.12 acres (one acre and twelve cents), without any prior encumbrances, for our family \nexpenses and to settle retail debts, for the amount of Rs. 5,50,000/- (Five lakh fifty \nthousand rupees).'}, {'text': 'The above purchase amount of Rs. 5,50,000/- (Five lakh fifty thousand rupees) has been \nreceived by us from you today as bank funds in the presence of the witnesses below, and \nwe \nhave \ntoday \nmade \nthe \nsaid \nproperty \nyour \nabsolute \nownership.'}, {'text': 'From tomorrow onwards, you shall get the title deed for the above purchased property \ntransferred in your name, pay the necessary taxes and other dues, and enjoy the property \nwith full freedom and perpetuity, along with all transactions such as purchase, gift, and \ninheritance by your sons, grandsons, and descendants as per your wish. Further, neither \nwe nor any of our minor or major heirs shall have any share, freedom, or right whatsoever \nin the above property, and we have not created any encumbrance or dependency on the \nsaid property. If there is any encumbrance or any civil or criminal case known to exist, we \nourselves will resolve it at our own expense. Our sincere and agreed purchase deed has \nbeen written and signed accordingly.'}, {'text': 'The above-mentioned purchased property falls under Kelamangalam Union, \nThottathimmanahall Panchayat jurisdiction.'}, {'text': 'Details of the purchased property'}, {'text': 'Krishnagiri Reedy, Rayakottai Sub Reedy, Krishnagiri District. Thenkanikkottai Taluk, \nNellur Village Survey No. 7/5A (Seven / Five A) land. Hectares 0.45.5 with a value of Rs. \n1.25 per unit. This corresponds to land measuring 1.12 acres (One acre twelve cents) \nfully owned (according to document numbers 335/1989 & 1205/2021, land measuring \n0.56 acres cents, and according to Patta No. 907, land measuring 0.56 acres cents) along \nwith the customary pathway leading to the above land, including the above-mentioned \nroad, is subject to clear purchase.'}, {'text': 'The current market value of the above-purchased property is Rs. 5,61,120/-.'}, {'text': '1. (Sakkappan) Th/P Muniyappan. Ullatti Village .'}, {'text': '2. (Senthaayappan) Th/Pe Rajappan, Ullatti Village .'}, {'text': "Sale Agreement Document \nSale Amount Rs. 1,20,000/- \nAdvance Payment Rs. 20,000/- \nGrace Period 2 years \nOn 13.02.2026 (the year two thousand twenty-six, February month, \nthirteenth day) in Krishnagiri district, Sulagiri taluk, Uthanapalli post. \nVenkatesapuram village. Door number 1/1116, residing Ayyappa's son \nAshok. \nIn Krishnagiri district, Sulagiri taluk, Uthanapalli post, Devasanapalli village, \ndoor number 1302A, residing Chinnadurai's son C. Arivazhagan. the two of \nus have mutually agreed and written this sale agreement document as \nfollows: \nEven now, two of us have independently purchased the property described \nunder document number 3095/2021 at the Rayakottai Sub-Registrar's \nOffice, based on the individual freehold experience of two persons. Out of \nthis, one of us has agreed to buy the detailed property for Rs. 1,20,000/- (One \nlakh twenty thousand rupees). Out of the above purchase amount, an \nadvance of Rs. 20,000/- (Twenty thousand rupees) has been paid by one \nperson to the other two persons, who have received the cash and signed the \nagreement document. The remaining balance purchase amount of Rs. \n1,00,000/- (One lakh rupees) shall be paid by one person to the other two \npersons within 2 (two) years from today, and the purchase registration must \nbe done in the name of either the one person or the person requested by him \nby the two persons. If, within the said period, the balance purchase amount \nis paid by one person to the other two persons and the purchase registration \nis done, even if the two persons demand a higher purchase amount or delay \nthe registration citing excuses, one person has the right to file this agreement \ndocument and the balance amount in the relevant court without expecting \ncooperation from the two persons. The two persons have no right to object \nto the compulsory registration by one person or to the freehold of the \nproperty by one person. Our consent has been given and the purchase"}, {'text': 'agreement document has been signed accordingly. The above property has \nnot been given freehold yet. \n                                            Property  Details'}, {'text': 'Krishnagiri Reedy. Rayakottai Sabreedy. Krishnagiri District. Sulagiri Taluk. \nUthanapalli Village Survey No. 682/2 (Six hundred eighty-two / two) land, \nHect. 0.14.0 with a value of Rs. 0.45. Within this, new subdivision Survey \nNo. 682/2B2 (Six hundred eighty-two / two B two) land Hect. 0.01.20 with a \nvalue of Rs. 0.10. Patta No. 3098. Details of boundaries are as follows: \nEast- Survey No. 683 land \nWest - Land left for pathway \nNorth - Manjula. Venkatesh land \nSouth - Survey No. 679/1 Arivazhagan land, Survey No.          \n682/3 land & Panchayat road \nIn the middle of this, there is a land measuring exactly Hect. 0.03 (three \ncents) with a well and also \nThe above Uthanappalli village survey number 679/1 (six hundred seventy-\nnine / one) land area 0.01 hectares has a resolution of Rs.0.06, Patta \nnumber 3098. Correspondingly, land with an area of 0.02% hectares (two \nand a half cents) including the pond and combined in the above two survey \nnumbers, land with an area of 0.05½ hectares (five and a half cents) \nincluding the usual pathway leading to the above lands is subject to the \nabove road purchase agreement document.'}, {'text': 'The current market value of the above properties is Rs.1,20,000/-'}, {'text': '1. (Murugesh) Th/P Muniyappa, Uthanappalli village. \n2. (Santhamma) K/Pe Rajendran. Thuppukanappalli village.'}, {'text': "Clean Sale Deed \n13.02.2026 (Two thousand twenty-sixth year. February month. Thirteenth day) \nDharmapuri District, Pappirettipatti Taluk. Pommidi Post. Pommidi. B-Dhruñchipatti. \nBoyar Street Door No. 3/222, residing Raja's wife Jayamani to you \nKarnataka State, Bengaluru District. Anekal Taluk. Anekal Thali Road, Thikala \nStreet, Ward No. 2, residing Ledramakrishnappa's son Ramesh  I have willingly written \nand given this clean sale deed which means \nEven now, at the Rayakottai Sub-Registrar Office, document No. 5169/2025, as a \nD-Schedule document, based on which I have been in free possession until yesterday, \nthe property detailed therein without any prior encumbrance, for my family expenses and \nagricultural expenses, I have agreed to sell to you for Rs. 1,00,000/- (One lakh two \nhundred) rupees, and the above sale amount Rs. 100,200/- (Two lakh two hundred) \nrupees I have received from you today in the presence of the following witnesses and I \nhave today made the below property your freehold. \nFrom now on, on tomorrow's date itself, you shall transfer the title deed of the \nabove-mentioned purchased property into your name. You shall pay all the necessary \ntaxes and other charges and enjoy the property freely and eternally, along with all the \nrights of inheritance through your sons, grandsons, and lineage, with full freedom and \nas per your wish, including all transactions like gifts and transfers. Henceforth, neither I \nnor any of my minor or major heirs shall have any right, claim, or freedom over the said \nproperty, and I have not created any kind of encumbrance or dependence on the said \nproperty. If there are any encumbrances or any civil or criminal cases related to this, I \nwill resolve them at my own expense. If any cases are hidden and documents are \nregistered, I agree to abide by the decisions taken by the honorable court in this regard. I \nhereby confirm this, and I have willingly signed and executed this clean sale deed."}, {'text': 'The above-mentioned purchased property falls under the jurisdiction of Sulagiri \nUnion, Thuppukanapalli Panchayat.'}, {'text': 'Krishnagiri Reddy. Rayakottai Sub Reddy. Krishnagiri District. Sulagiri Taluk. \nThuppukanappalli Village Survey No. 295 (Two hundred ninety-five) Land, Hectare \n0.98.5 with a price of Rs. 0.61. In this, new subdivision Survey No. 295/2 (Two hundred \nninety-five / two) Land Hectare 0.24,64 with a price of Rs. 0.15. Details of boundaries: \n                                      East - Survey No. 295/3 Land \n                                      West - Muthuraj Land \n                                      North - Remaining land in the same survey number \n                                      South - Survey No. 296 Adjacent land \nIn the middle of this, land of 0.20 acres (twenty cents) with a path leading to the above \nland including a common pathway is included in the clear sale.'}, {'text': 'The current market value of the above sale property is Rs. 1,00,200/-.'}, {'text': '1. (Senthilkumar) S/o Chinnappa, Utthanappalli Village.'}, {'text': '2. (Venkatesh) S/o Gopalappa, Chinnalakshmipuram Village.'}, {'text': '26.09.2025 (September, twenty-sixth, year two thousand and twenty-five) To you, N. Durai \nNagaraj, son of Nagaraj, residing at Door No. 4/155, Village Koothandahalli, Nammanthahalli \nPost Office, Palacode Taluk, Dharmapuri District'}, {'text': "The following is the pure purchase deed written by us, Late Thottayan's wife \nMuniyammal.1residing at Door No. 5/227, Thottatimmanahalli Post Office, Palakodu Taluk, \nDharmapuri District, and the sons of the above 1 lakh Muniyammal & Late Thottayan, \nSakthivel, Bhagyaraj. , Ajithkumar."}, {'text': "Now, the deceased Thottayan, who is the husband of 1 lakh people among us and the father \nof 2 to 4 lakh people, has obtained the property in the Rayakottai Registrar's Office as \nDocument No. 2296/2015 as the basis of the purchase document. After the death of the said \nThottayan (15.05.2021), the inheritance certificate No. was obtained by the Palakodu \nVatachiyar. As per TN-720210612721, we, the heirs of the 1st to 4th lakhs, have been allotted \nthe property mentioned herein, which has been acquired by us from our joint ownership \nexperience till date, without any prior reservation, for our family expenses and agricultural \nexpenses, at a cost of Rs. 1,79,000/- (one lakh seventy nine thousand) rupees, and the above \ncost amount is Rs. 1,79,000/- (one lakh seventy nine thousand) We have received from you \ntoday in the presence of the following witnesses the sum of Rs. 1913155000028662 through \nCheque No. 000003 drawn from Karur Vysya Bank, Rayakottai Branch Savings Account No. \n1913155000028662 and have also taken possession of the following properties today."}, {'text': 'From now on, you shall transfer the title deed for the above properties to your name, pay the \ndues, taxes, etc., and enjoy them in perpetuity with complete freedom and with all \ntransactions as you wish, including purchases, donations, etc., as per your will. \nFurthermore, we and our minor or major heirs have no right, title or interest in the above \nproperties, and we have not committed any encroachment on the above properties, and we \nwill settle any such encroachment, civil or criminal cases, if any, at our own expense. This is \na clean purchase deed that we have written down in our minds.The above purchase \nproperties are within the limits of Palacode Union, Kummanur Panchayat.'}, {'text': 'Purchase Property Details \nKrishnagiri Reedy, Rayakottai Sub-Reedy, Dharmapuri District, Palacode Taluk, \nChinnegaundanahalli Village Survey No. 87/1A (Eighty Seven / One A) Land 1.41.5 with a tax \nof Rs. 3.92, out of which new subdivision Survey No. 87/1A1 (Eighty Seven / One A) Land \n1.27.75 with a tax of Rs. 3.54, out of which the cross-section details are \nEast - Krishnan Land \nWest - Suresh Land \nNorth - Suresh Land \nSouth - Thottayan Land \nIn the middle of this, a land measuring 0.38 (thirty-eight cents) and'}]

In [ ]:
from datasets import Dataset
dataset = Dataset.from_list(data)

In [ ]:
dataset

Dataset({
    features: ['text'],
    num_rows: 28
})

In [ ]:


# model_name = "meta-llama/Llama-2-7b-hf"
# model_name = "meta-llama/Llama-3.1-8B"
model_name = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments, DataCollatorForLanguageModeling

In [ ]:


tokenizer = AutoTokenizer.from_pretrained(model_name)

In [ ]:
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

In [ ]:


def tokenize_fn(examples):
    tokens = tokenizer(examples["text"],truncation=True,padding="max_length",max_length=512)
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

In [ ]:


tokenized = dataset.map(tokenize_fn, batched=True, remove_columns=["text"])

Map:   0%|          | 0/28 [00:00<?, ? examples/s]

In [ ]:
tokenized

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 28
})

In [ ]:
from transformers import BitsAndBytesConfig
import torch

quantization_config = BitsAndBytesConfig(
    load_in_8bit=True
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    device_map="auto"
)

model.safetensors:   0%|          | 0.00/4.40G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/129 [00:00<?, ?B/s]

In [ ]:
training_args = TrainingArguments(
    output_dir="./llama-legal-domain",
    num_train_epochs=2,
    per_device_train_batch_size=1, # Reduced batch size
    save_steps=500,
    save_total_limit=2,
    logging_steps=50,
    learning_rate=2e-5,
    fp16=True,
    report_to="none"
)

In [ ]:


from transformers import TrainingArguments
help(TrainingArguments)

Help on class TrainingArguments in module transformers.training_args:

class TrainingArguments(builtins.object)
 |  TrainingArguments(output_dir: str | None = None, per_device_train_batch_size: int = 8, num_train_epochs: float = 3.0, max_steps: int = -1, learning_rate: float = 5e-05, lr_scheduler_type: transformers.trainer_utils.SchedulerType | str = 'linear', lr_scheduler_kwargs: dict | str | None = None, warmup_steps: float = 0, optim: transformers.training_args.OptimizerNames | str = 'adamw_torch_fused', optim_args: str | None = None, weight_decay: float = 0.0, adam_beta1: float = 0.9, adam_beta2: float = 0.999, adam_epsilon: float = 1e-08, optim_target_modules: None | str | list[str] = None, gradient_accumulation_steps: int = 1, average_tokens_across_devices: bool = True, max_grad_norm: float = 1.0, label_smoothing_factor: float = 0.0, bf16: bool = False, fp16: bool = False, bf16_full_eval: bool = False, fp16_full_eval: bool = False, tf32: bool | None = None, gradient_checkpointing: bool = False, gradient_checkpointing_kwargs: dict[str, typing.Any] | str | None = None, torch_compile: bool = False, torch_compile_backend: str | None = None, torch_compile_mode: str | None = None, use_liger_kernel: bool = False, liger_kernel_config: dict[str, bool] | None = None, use_cache: bool = False, neftune_noise_alpha: float | None = None, torch_empty_cache_steps: int | None = None, auto_find_batch_size: bool = False, logging_strategy: transformers.trainer_utils.IntervalStrategy | str = 'steps', logging_steps: float = 500, logging_first_step: bool = False, log_on_each_node: bool = True, logging_nan_inf_filter: bool = True, include_num_input_tokens_seen: str | bool = 'no', log_level: str = 'passive', log_level_replica: str = 'warning', disable_tqdm: bool | None = None, report_to: None | str | list[str] = 'none', run_name: str | None = None, project: str = 'huggingface', trackio_space_id: str | None = 'trackio', eval_strategy: transformers.trainer_utils.IntervalStrategy | str = 'no', eval_steps: float | None = None, eval_delay: float = 0, per_device_eval_batch_size: int = 8, prediction_loss_only: bool = False, eval_on_start: bool = False, eval_do_concat_batches: bool = True, eval_use_gather_object: bool = False, eval_accumulation_steps: int | None = None, include_for_metrics: list[str] = <factory>, batch_eval_metrics: bool = False, save_only_model: bool = False, save_strategy: transformers.trainer_utils.SaveStrategy | str = 'steps', save_steps: float = 500, save_on_each_node: bool = False, save_total_limit: int | None = None, enable_jit_checkpoint: bool = False, push_to_hub: bool = False, hub_token: str | None = None, hub_private_repo: bool | None = None, hub_model_id: str | None = None, hub_strategy: transformers.trainer_utils.HubStrategy | str = 'every_save', hub_always_push: bool = False, hub_revision: str | None = None, load_best_model_at_end: bool = False, metric_for_best_model: str | None = None, greater_is_better: bool | None = None, ignore_data_skip: bool = False, restore_callback_states_from_checkpoint: bool = False, full_determinism: bool = False, seed: int = 42, data_seed: int | None = None, use_cpu: bool = False, accelerator_config: dict | str | None = None, parallelism_config: accelerate.parallelism_config.ParallelismConfig | None = None, dataloader_drop_last: bool = False, dataloader_num_workers: int = 0, dataloader_pin_memory: bool = True, dataloader_persistent_workers: bool = False, dataloader_prefetch_factor: int | None = None, remove_unused_columns: bool = True, label_names: list[str] | None = None, train_sampling_strategy: str = 'random', length_column_name: str = 'length', ddp_find_unused_parameters: bool | None = None, ddp_bucket_cap_mb: int | None = None, ddp_broadcast_buffers: bool | None = None, ddp_backend: str | None = None, ddp_timeout: int = 1800, fsdp: list[transformers.trainer_utils.FSDPOption] | str | None = None, fsdp_config: dict[str, typing.Any] | str | None = None, deepspeed: dict | str | None = None, debug: str | list[transformers.debug_utils.DebugOption] = '', skip_memory_metrics: bool = True, do_train: bool = False, do_eval: bool = False, do_predict: bool = False, resume_from_checkpoint: str | None = None, warmup_ratio: float | None = None, logging_dir: str | None = None, local_rank: int = -1) -> None
 |
 |  Configuration class for controlling all aspects of model training with the Trainer.
 |  TrainingArguments centralizes all hyperparameters, optimization settings, logging preferences, and infrastructure choices needed for training.
 |
 |  [`HfArgumentParser`] can turn this class into
 |  [argparse](https://docs.python.org/3/library/argparse#module-argparse) arguments that can be specified on the
 |  command line.
 |
 |  Parameters:
 |      output_dir (`str`, *optional*, defaults to `"trainer_output"`):
 |          The output directory where the model predictions and checkpoints will be written.
 |
 |      > Training Duration and Batch Size
 |
 |      per_device_train_batch_size (`int`, *optional*, defaults to 8):
 |          The batch size *per device*. The **global batch size** is computed as:
 |          `per_device_train_batch_size * number_of_devices` in multi-GPU or distributed setups.
 |      num_train_epochs(`float`, *optional*, defaults to 3.0):
 |          Total number of training epochs to perform (if not an integer, will perform the decimal part percents of
 |          the last epoch before stopping training).
 |      max_steps (`int`, *optional*, defaults to -1):
 |          Overrides `num_train_epochs`. If set to a positive number, the total number of training steps to perform.
 |          For a finite dataset, training is reiterated through the dataset (if all data is exhausted) until
 |          `max_steps` is reached.
 |
 |      > Learning Rate & Scheduler
 |
 |      learning_rate (`float`, *optional*, defaults to 5e-5):
 |          The initial learning rate for the optimizer. This is typically the peak learning rate when using a scheduler with warmup.
 |      lr_scheduler_type (`str` or [`SchedulerType`], *optional*, defaults to `"linear"`):
 |          The learning rate scheduler type to use. See [`SchedulerType`] for all possible values. Common choices:
 |              - "linear" = [`get_linear_schedule_with_warmup`]
 |              - "cosine" = [`get_cosine_schedule_with_warmup`]
 |              - "constant" =  [`get_constant_schedule`]
 |              - "constant_with_warmup" = [`get_constant_schedule_with_warmup`]
 |      lr_scheduler_kwargs (`dict` or `str`, *optional*, defaults to `None`):
 |          The extra arguments for the lr_scheduler. See the documentation of each scheduler for possible values.
 |      warmup_steps (`int` or `float`, *optional*, defaults to 0):
 |          Number of steps for a linear warmup from 0 to `learning_rate`. Warmup helps stabilize training in the initial phase. Can be:
 |              - An integer: exact number of warmup steps
 |              - A float in range [0, 1): interpreted as ratio of total training steps
 |
 |      > Optimizer
 |
 |      optim (`str` or [`training_args.OptimizerNames`], *optional*, defaults to `"adamw_torch"` (for torch>=2.8 `"adamw_torch_fused"`)):
 |          The optimizer to use. Common options:
 |              - `"adamw_torch"`: PyTorch's AdamW (recommended default)
 |              - `"adamw_torch_fused"`: Fused AdamW kernel
 |              - `"adamw_hf"`: HuggingFace's AdamW implementation
 |              - `"sgd"`: Stochastic Gradient Descent with momentum
 |              - `"adafactor"`: Memory-efficient optimizer for large models
 |              - `"adamw_8bit"`: 8-bit AdamW (requires bitsandbytes)
 |              See [`OptimizerNames`] for the complete list.
 |      optim_args (`str`, *optional*):
 |          Optional arguments that are supplied to optimizers such as AnyPrecisionAdamW, AdEMAMix, and GaLore.
 |      weight_decay (`float`, *optional*, defaults to 0):
 |          Weight decay coefficient applied by the optimizer (not the loss function). Adds L2
 |          regularization to prevent overfitting by penalizing large weights. Automatically
 |          excluded from bias and LayerNorm parameters. Typical values: 0.01 (standard), 0.1
 |          (stronger regularization), 0.0 (no regularization).
 |      adam_beta1 (`float`, *optional*, defaults to 0.9):
 |          The exponential decay rate for the first moment estimates (momentum) in Adam-based
 |          optimizers. Controls how much history of gradients to retain.
 |      adam_beta2 (`float`, *optional*, defaults to 0.999):
 |          The exponential decay rate for the second moment estimates (variance) in Adam-based
 |          optimizers. Controls adaptive learning rate scaling.
 |      adam_epsilon (`float`, *optional*, defaults to 1e-8):
 |          Epsilon value for numerical stability in Adam-based optimizers. Prevents division by
 |          zero in the denominator of the update rule.
 |      optim_target_modules (`Union[str, list[str]]`, *optional*):
 |          The target modules to optimize, i.e. the module names that you would like to train.
 |          Currently used for the [GaLore algorithm](https://huggingface.co/papers/2403.03507) and [APOLLO algorithm](https://huggingface.co/papers/2412.05270).
 |          See [GaLore implementation](https://github.com/jiaweizzhao/GaLore) and [APOLLO implementation](https://github.com/zhuhanqing/APOLLO) for more details.
 |          You need to make sure to pass a valid GaLore or APOLLO optimizer, e.g., one of: "apollo_adamw", "galore_adamw", "galore_adamw_8bit", "galore_adafactor" and make sure that the target modules are `nn.Linear` modules only.
 |
 |      > Regularization & Training Stability
 |
 |      gradient_accumulation_steps (`int`, *optional*, defaults to 1):
 |          Number of update steps to accumulate gradients before performing a backward/update pass.
 |          Simulates larger batch sizes without additional memory. Effective batch size =
 |          `per_device_train_batch_size × num_devices × gradient_accumulation_steps`.
 |          > [!TIP]
 |          > When using gradient accumulation, one "step" is counted as one step with a backward pass. Therefore, logging, evaluation, and saving will occur every `gradient_accumulation_steps × xxx_step` training examples.
 |      average_tokens_across_devices (`bool`, *optional*, defaults to `True`):
 |          Whether or not to average tokens across devices. If enabled, will use all_reduce to synchronize
 |          num_tokens_in_batch for precise loss calculation. Reference:
 |          https://github.com/huggingface/transformers/issues/34242
 |      max_grad_norm (`float`, *optional*, defaults to 1.0):
 |          Maximum gradient norm for gradient clipping. Applied after backward pass, before
 |          optimizer step. Prevents gradient explosion by scaling down gradients when their global
 |          norm exceeds this threshold. Set to 0 to disable clipping. Typical values:
 |          1.0 (standard), 0.5 (more conservative), 5.0 (less aggressive).
 |      label_smoothing_factor (`float`, *optional*, defaults to 0.0):
 |          Label smoothing factor to prevent overconfidence. Replaces hard 0/1 targets with soft
 |          targets: 0 becomes `ε/num_labels` and 1 becomes `1 - ε + ε/num_labels`, where
 |          ε = `label_smoothing_factor`. Zero means no smoothing. Typical range: 0.0 to 0.1.
 |
 |      > Mixed Precision Training
 |
 |      bf16 (`bool`, *optional*, defaults to `False`):
 |          Enable bfloat16 (BF16) mixed precision training
 |          Generally preferred over FP16 due to better numerical stability and no loss scaling required.
 |      fp16 (`bool`, *optional*, defaults to `False`):
 |          Enable float16 (FP16) mixed precision training.
 |          Consider using BF16 instead if your hardware supports it.
 |      bf16_full_eval (`bool`, *optional*, defaults to `False`):
 |          Use full BF16 precision for evaluation (not just mixed precision). Faster and saves
 |          memory but may affect metric values slightly. Only applies during evaluation.
 |      fp16_full_eval (`bool`, *optional*, defaults to `False`):
 |          Use full FP16 precision for evaluation (not just mixed precision). Faster and saves
 |          memory but may affect metric values slightly. Only applies during evaluation.
 |      tf32 (`bool`, *optional*):
 |          Enable TensorFloat-32 (TF32) mode on Ampere and newer GPUs. TF32 uses 19-bit precision
 |          for matrix multiplications (instead of FP32's 23-bit), providing up to 8x speedup with
 |          negligible accuracy loss. Default depends on PyTorch version. See
 |          [TF32 docs](https://huggingface.co/docs/transformers/perf_train_gpu_one#tf32).
 |
 |      > Gradient Checkpointing
 |
 |      gradient_checkpointing (`bool`, *optional*, defaults to `False`):
 |          Enable gradient checkpointing to trade compute for memory. Reduces memory usage by
 |          clearing activations during forward pass and recomputing them during backward pass.
 |          Enables training larger models or batch sizes at the cost of ~20% slower training.
 |      gradient_checkpointing_kwargs (`dict`, *optional*, defaults to `None`):
 |          Keyword arguments passed to `gradient_checkpointing_enable()`.
 |
 |      > Compilation
 |
 |      torch_compile (`bool`, *optional*, defaults to `False`):
 |          Compile the model using PyTorch 2.0's `torch.compile()` for faster training. Can provide
 |          20-50% speedup with no code changes. Uses default compilation settings unless
 |          `torch_compile_backend` or `torch_compile_mode` are specified.
 |      torch_compile_backend (`str`, *optional*):
 |          Backend for `torch.compile()`. If set, automatically enables `torch_compile`. Options
 |          include `"inductor"` (default), `"aot_eager"`, `"cudagraphs"`. Backends vary by PyTorch
 |          version - see PyTorch docs for available options.
 |      torch_compile_mode (`str`, *optional*):
 |          Compilation mode for `torch.compile()`. If set, automatically enables `torch_compile`.
 |          Options: `"default"`, `"reduce-overhead"` (minimize Python overhead), `"max-autotune"`
 |          (aggressive optimization, slower compile time).
 |
 |      > Kernels
 |
 |      use_liger_kernel (`bool`, *optional*, defaults to `False`):
 |          Enable [Liger Kernel](https://github.com/linkedin/Liger-Kernel) optimizations. Increases
 |          multi-GPU throughput by ~20% and reduces memory usage by ~60%. Works with Flash Attention,
 |          FSDP, and DeepSpeed. Currently supports Llama, Mistral, Mixtral, and Gemma models.
 |      liger_kernel_config (`Optional[dict]`, *optional*):
 |          Configuration for Liger Kernel. Passed as kwargs to `_apply_liger_kernel_to_instance()`.
 |          Options typically include: `"rope"`, `"swiglu"`, `"cross_entropy"`,
 |          `"fused_linear_cross_entropy"`, `"rms_norm"`. If `None`, uses default configuration.
 |
 |      > Additional Optimizations
 |
 |      use_cache (`bool`, *optional*, defaults to `False`):
 |          Whether or not to enable cache for the model. For training, this is usually not needed apart from some PEFT methods that uses `past_key_values`.
 |      neftune_noise_alpha (`Optional[float]`):
 |          If not `None`, this will activate NEFTune noise embeddings. This can drastically improve model performance
 |          for instruction fine-tuning. Check out the [original paper](https://huggingface.co/papers/2310.05914) and the
 |          [original code](https://github.com/neelsjain/NEFTune). Support transformers `PreTrainedModel` and also
 |          `PeftModel` from peft. The original paper used values in the range [5.0, 15.0].
 |      torch_empty_cache_steps (`int`, *optional*):
 |          Number of steps to wait before calling `torch.<device>.empty_cache()`. If left unset or set to None, cache will not be emptied.
 |          This can help avoid CUDA out-of-memory errors by lowering peak VRAM usage at a cost of about [10% slower performance](https://github.com/huggingface/transformers/issues/31372).
 |      auto_find_batch_size (`bool`, *optional*, defaults to `False`)
 |          Whether to find a batch size that will fit into memory automatically through exponential decay, avoiding
 |          CUDA Out-of-Memory errors.
 |
 |      > Logging & Monitoring Training
 |
 |      logging_strategy (`str` or [`~trainer_utils.IntervalStrategy`], *optional*, defaults to `"steps"`):
 |          The logging strategy to adopt during training. Possible values are:
 |              - `"no"`: No logging is done during training.
 |              - `"epoch"`: Logging is done at the end of each epoch.
 |              - `"steps"`: Logging is done every `logging_steps`.
 |      logging_steps (`int` or `float`, *optional*, defaults to 500):
 |          Number of update steps between two logs if `logging_strategy="steps"`. Should be an integer or a float in
 |          range `[0,1)`. If smaller than 1, will be interpreted as ratio of total training steps.
 |      logging_first_step (`bool`, *optional*, defaults to `False`):
 |          Whether to log the first `global_step` or not.
 |      log_on_each_node (`bool`, *optional*, defaults to `True`):
 |          In multinode distributed training, whether to log using `log_level` once per node, or only on the main
 |          node.
 |      logging_nan_inf_filter (`bool`, *optional*, defaults to `True`):
 |           Filter out NaN and Inf losses when logging. If `True`, replaces NaN/Inf losses with the
 |          average of recent valid losses. Does not affect gradient computation, only logging.
 |      include_num_input_tokens_seen (`Optional[Union[str, bool]]`, *optional*, defaults to "no"):
 |          Whether to track the number of input tokens seen. Must be one of ["all", "non_padding", "no"] or a boolean value which map to "all" or "no".
 |          May be slower in distributed training as gather operations must be called.
 |
 |      > Logging
 |
 |      log_level (`str`, *optional*, defaults to `passive`):
 |          Logging level for the main process. Options: `"debug"`, `"info"`, `"warning"`, `"error"`,
 |          `"critical"`, or `"passive"` (doesn't change the current Transformers logging level,
 |          which defaults to `"warning"`)
 |      log_level_replica (`str`, *optional*, defaults to `"warning"`):
 |          Logging level for replica processes in distributed training. Same options as `log_level`.
 |      disable_tqdm (`bool`, *optional*):
 |          Disable tqdm progress bars. Defaults to `True` if `log_level` is warning or lower, `False` otherwise.
 |
 |      > Experiment Tracking Integration
 |
 |      report_to (`str` or `list[str]`, *optional*, defaults to `"none"`):
 |          The list of integrations to report the results and logs to. Supported platforms are `"azure_ml"`,
 |          `"clearml"`, `"codecarbon"`, `"comet_ml"`, `"dagshub"`, `"dvclive"`, `"flyte"`, `"mlflow"`, `"swanlab"`,
 |          `"tensorboard"`, `"trackio"` and `"wandb"`. Use `"all"` to report to all integrations installed, `"none"`
 |          for no integrations.
 |      run_name (`str`, *optional*):
 |          A descriptor for the run. Typically used for [trackio](https://github.com/gradio-app/trackio),
 |          [wandb](https://www.wandb.com/), [mlflow](https://www.mlflow.org/), [comet](https://www.comet.com/site) and
 |          [swanlab](https://swanlab.cn) logging.
 |      project (`str`, *optional*, defaults to `"huggingface"`):
 |          The name of the project to use for logging. Currently, only used by Trackio.
 |      trackio_space_id (`str` or `None`, *optional*, defaults to `"trackio"`):
 |          The Hugging Face Space ID to deploy to when using Trackio. Should be a complete Space name like
 |          `'username/reponame'` or `'orgname/reponame'`, or just `'reponame'` in which case the Space will be

In [ ]:
from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    target_modules=["q_proj","v_proj"],
    lora_dropout=0.05,
    bias="none"
)

q_lora_model= get_peft_model(model, lora_config)

trainer = Trainer(
    model=q_lora_model,
    args=training_args,
    train_dataset=tokenized
)

In [ ]:
trainer.train()
q_lora_model.save_pretrained(training_args.output_dir)

/usr/local/lib/python3.12/dist-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")

In [ ]:

import torch, gc
gc.collect()
torch.cuda.empty_cache()

In [ ]:
!pip install -U peft bitsandbytes transformers accelerate

Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft) (4.67.3)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.7.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.4.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (3.24.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft) (1.3.4)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (0.24.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (0.1.2)

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
from peft import LoraConfig, get_peft_model, TaskType
from datasets import load_dataset

In [ ]:
model = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model)

In [ ]:
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

In [ ]:
def tokenize_fn(examples):
    tokens = tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=512
    )
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

In [ ]:
tokenized = dataset.map(tokenize_fn, batched=True)

Map:   0%|          | 0/28 [00:00<?, ? examples/s]

In [ ]:


tokenized

Dataset({
    features: ['text', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 28
})

In [ ]:
pip

In [ ]:
from transformers import BitsAndBytesConfig
import torch

quantization_config = BitsAndBytesConfig(
    load_in_8bit=True
)

model = AutoModelForCausalLM.from_pretrained(
    model,
    quantization_config=quantization_config,
    device_map="auto"
)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    target_modules=["q_proj","v_proj"],
    lora_dropout=0.05,
    bias="none"
)

In [ ]:
q_lora_model= get_peft_model(model, lora_config)

In [ ]:
args = TrainingArguments(
    output_dir="./tinyllama-lora",
    num_train_epochs=5,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=20,
    save_total_limit=1,
    report_to="none"
)

In [ ]:


trainer = Trainer(
    model=q_lora_model,
    args=args,
    train_dataset=tokenized
)

In [ ]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")

TrainOutput(global_step=20, training_loss=7.723188781738282, metrics={'train_runtime': 81.4286, 'train_samples_per_second': 1.719, 'train_steps_per_second': 0.246, 'total_flos': 445407528222720.0, 'train_loss': 7.723188781738282, 'epoch': 5.0})

In [ ]:
model="/content/llama-legal-domain"

In [ ]:
# First, load the base model again
base_model = AutoModelForCausalLM.from_pretrained(
    model_name, # Use the original model name
    quantization_config=quantization_config,
    device_map="auto"
)

# Load the LoRA adapters from the saved directory
from peft import PeftModel
lora_model = PeftModel.from_pretrained(base_model, model)

# Merge the LoRA adapters with the base model
merged_model = lora_model.merge_and_unload()

# Now, `merged_model` is your fully fine-tuned model
# You can save it or use it for inference
print("LoRA adapters merged successfully into the base model.")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/bnb.py:110: UserWarning: Merge lora module to 8-bit linear may get different generations due to rounding errors.
  warnings.warn(

LoRA adapters merged successfully into the base model.

In [ ]:

prompt = "Clean deed documents for finding duplicates,inconsistencies and contradcitions"

In [ ]:
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

In [ ]:
outputs = merged_model.generate(
    **inputs,
    max_new_tokens=100,
    temperature=0.8,
    top_p=0.9,
    do_sample=True,
    repetition_penalty=1.1
)

/usr/local/lib/python3.12/dist-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")

In [ ]:
print("\nModel Output:\n")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Model Output:

Clean deed documents for finding duplicates,inconsistencies and contradcitions.
I think that the best way to resolve this situation is to go back to the very beginning of the history of the United States, to 1776.
It was then that the first treaty between the United States and Great Britain was signed in Paris, which provided a legal basis for the "division" of North America.
Since this document was not ratified by the United States Congress until April 25, 1789, and since it had

In [ ]:
import shutil
from google.colab import files

# Zip the directory containing the saved model
shutil.make_archive("tinyllama-lora", "zip", "./tinyllama-lora")

# Now download the zipped file
files.download("tinyllama-lora.zip")

In [ ]:
instruction fine tuning

In [ ]:


from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
from peft import LoraConfig, get_peft_model, TaskType
from datasets import load_dataset

In [ ]:
model = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"

In [ ]:


tokenizer = AutoTokenizer.from_pretrained(model)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

In [ ]:

import zipfile
import os
# Path to your zip file
zip_path = "/content/tinyllama-lora.zip"

# Extract all files
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall()

In [ ]:
model_path = "/content/checkpoint-20"

In [ ]:
non_instruction_model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/88 [00:00<?, ?it/s]

In [ ]:
prompt = "Clean deed documents for finding duplicates,inconsistencies and contradcitions"

In [ ]:
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

In [ ]:


outputs = non_instruction_model.generate(
    **inputs,
    max_new_tokens=100,
    temperature=0.8,
    top_p=0.9,
    do_sample=True,
    repetition_penalty=1.1
)

In [ ]:
print("\nModel Output:\n")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Model Output:

Clean deed documents for finding duplicates,inconsistencies and contradcitions,and it can be easily used as a search engine to look up for a specific document or a set of documents.
The system is designed to work with the most popular tools, such as Windows Explorer and Microsoft Word.It also supports other common applications like Google Chrome and Mozilla Firefox.
The application also has an optional free plugin for Outlook 2013, allowing to add attachments to mail messages and copy them directly from the message into the document searcher.
An

In [ ]:
from datasets import Dataset
import pandas as pd

file_paths = [
    "/content/Contradiction.xlsx",
    "/content/Duplication.xlsx",
    "/content/Inconsistency.xlsx"
]

# Load each Excel file into a pandas DataFrame and store them in a list
dfs = []
for file_path in file_paths:
    df = pd.read_excel(file_path)
    dfs.append(df)

# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dfs, ignore_index=True)

# Convert the pandas DataFrame to a datasets.Dataset object
dataset = Dataset.from_pandas(combined_df)
dataset

Dataset({
    features: ['SENTENCE 1', 'SENTENCE 2', 'LABEL'],
    num_rows: 344
})

In [ ]:
def format_example(example):
    prompt = f"### SENTENCE 1:\n{example['SENTENCE 1']}\n### SENTENCE 2:\n{example['SENTENCE 2']}\n### LABEL:\n{example['LABEL']}"
    return {"text": prompt}

In [ ]:
dataset = dataset.map(format_example)

Map:   0%|          | 0/344 [00:00<?, ? examples/s]

In [ ]:
dataset

Dataset({
    features: ['SENTENCE 1', 'SENTENCE 2', 'LABEL', 'text'],
    num_rows: 344
})

In [ ]:


dataset['text'][0]

'### SENTENCE 1:\nThe land extent is 1.12 acres.\n### SENTENCE 2:\nThe land extent is 2.00 acres.\n### LABEL:\n0'

In [ ]:
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

In [ ]:

def tokenize_fn(example):
    tokens = tokenizer(example["text"], truncation=True, padding="max_length", max_length=512)
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

In [ ]:


tokenized = dataset.map(tokenize_fn, batched=True)

Map:   0%|          | 0/344 [00:00<?, ? examples/s]

In [ ]:
from peft import LoraConfig, get_peft_model, TaskType

In [ ]:
  lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
    bias="none"
)

In [ ]:
instruction_model = get_peft_model(non_instruction_model, lora_config)

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

In [ ]:
args = TrainingArguments(
    output_dir="./tinyllama-instruction",
    num_train_epochs=3,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=20,
    save_total_limit=1,
    report_to="none"
)

In [ ]:
trainer = Trainer(
    model=instruction_model,
    args=args,
    train_dataset=tokenized,
)

In [ ]:
trainer.train()

TrainOutput(global_step=129, training_loss=1.1610703126404636, metrics={'train_runtime': 261.1913, 'train_samples_per_second': 3.951, 'train_steps_per_second': 0.494, 'total_flos': 3283289779470336.0, 'train_loss': 1.1610703126404636, 'epoch': 3.0})

In [ ]:


model_path = "/content/tinyllama-instruction"

In [ ]:
instruction_model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/88 [00:00<?, ?it/s]

In [ ]:


prompt = "Find duplication in the document."

In [ ]:

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

In [ ]:
outputs = instruction_model.generate(
    **inputs,
    max_new_tokens=100,
    temperature=0.8,
    top_p=0.9,
    do_sample=True,
    repetition_penalty=1.1
)

In [ ]:


print("\nModel Output:\n")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Model Output:

Find duplication in the document.

  * To search for duplicate text, in the **Search** pane, select **Text Search** from the **Search** group to open the **Text Search** dialog box. For more information about using this dialog box, see [Text Search](../../vsto/text-search.md).

  * To search for a substring of a word, in the **Find** pane, type the string you want to find. If no matches are found, then type

In [ ]:
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType, PeftModel
import torch
import gc # Import gc for memory management

# --- Data Preparation ---
dataset = load_dataset("csv", data_files="/content/train_sample_10rows.csv", split="train")

def format_example(example):
    prompt = f"### Instruction:\n{example['instruction']}\n### Input:\n{example['input']}\n### Response:\n{example['output']}"
    return {"text": prompt}
dataset = dataset.map(format_example)

# Tokenizer is already loaded (global `tokenizer`)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def tokenize_and_mask(example):
    text = example["text"]
    enc = tokenizer(text, truncation=True, padding="max_length", max_length=512)
    response_marker = "### Response:"
    response_start = text.find(response_marker)

    if response_start != -1:
        response_token_start = len(tokenizer(text[:response_start], add_special_tokens=False)["input_ids"])
    else:
        response_token_start = 0

    labels = enc["input_ids"].copy()
    labels[:response_token_start] = [-100] * response_token_start
    enc["labels"] = labels
    return enc

tokenized = dataset.map(tokenize_and_mask, batched=False)
print("Tokenization + masking done.")

# --- Instruction Fine-Tuning ---

# Clear GPU memory before applying new LoRA and training
# Delete previous models to free GPU memory
if 'model' in globals():
    del model
if 'q_lora_model' in globals():
    del q_lora_model
if 'merged_model' in globals():
    del merged_model
# It's also important to delete previous trainer and associated models if they are no longer needed
if 'trainer' in globals():
    del trainer

gc.collect()
torch.cuda.empty_cache()

# non_instruction_model (from cell g2NsFw5PmO-d) is the base for instruction tuning.
# It's a PeftModel loaded from /content/checkpoint-5.

# LoRA config for instruction tuning
lora_config_instruction = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
    bias="none"
)

# Apply the instruction-tuning LoRA config to the non_instruction_model
instruction_training_model = get_peft_model(non_instruction_model, lora_config_instruction)

# Training arguments (using the 'args' variable from previous cell QVFY-sRRl0z5)
training_args_instruction = TrainingArguments(
    output_dir="./tinyllama-instruction",
    num_train_epochs=3,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=20,
    save_total_limit=1,
    report_to="none",
    gradient_checkpointing=True # Enable gradient checkpointing for memory efficiency
)

trainer_instruction = Trainer(
    model=instruction_training_model,
    args=training_args_instruction,
    train_dataset=tokenized,
)

# Train the model
trainer_instruction.train()

# Save the instruction-tuned model (LoRA adapters) and tokenizer
trainer_instruction.save_model("/content/tinyllama-instruction")
tokenizer.save_pretrained("/content/tinyllama-instruction")

# --- Cleanup after training and before inference ---
del trainer_instruction
del instruction_training_model # Delete the training model
gc.collect()
torch.cuda.empty_cache()

# --- Inference and Comparison ---

# non_instruction_model (the globally loaded one from /content/checkpoint-5) is ready for inference.
# We need to explicitly load the base model to apply the instruction-tuned adapters for inference.

# Load base model with quantization for inference
quantization_config_inference = BitsAndBytesConfig(load_in_8bit=True)
base_model_for_inference = AutoModelForCausalLM.from_pretrained(
    "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T", # Original base model name
    quantization_config=quantization_config_inference,
    device_map="auto"
)

# Load the instruction-tuned adapters onto the base model
instruction_tuned_model_for_inference = PeftModel.from_pretrained(
    base_model_for_inference,
    "/content/tinyllama-instruction" # Path to the saved instruction-tuned adapters
)

# Test generation with an instruction-tuned prompt
prompt_instruction_test = "### Instruction:\n Detect duplication of land area values in the document.\n### Input:\n\n### Response:\n"
inputs_instruction_test = tokenizer(prompt_instruction_test, return_tensors="pt").to("cuda")

outputs_instruction_test = instruction_tuned_model_for_inference.generate(
    **inputs_instruction_test,
    max_new_tokens=100,
    temperature=0.8,
    top_p=0.9,
    do_sample=True,
    repetition_penalty=1.1
)
print("\nModel Output (Instruction-tuned):\n")
print(tokenizer.decode(outputs_instruction_test[0], skip_special_tokens=True))

# Iterate through questions for comparison
questions = [
    "Detect duplication of land area values in the document.",
    "Identify inconsistencies in property market value information.",
    "Find duplication in the document."
]

for q in questions:
    print(f"Question: {q}")

    # --- Non-instruction model (document-finetuned) ---
    print("\n--- Non-instruction model (document-finetuned) ---")
    inputs_non_inst = tokenizer(q, return_tensors="pt").to("cuda")
    # Use the globally available `non_instruction_model` from cell g2NsFw5PmO-d
    outputs_non_inst = non_instruction_model.generate(**inputs_non_inst, max_new_tokens=80)
    print(tokenizer.decode(outputs_non_inst[0], skip_special_tokens=True))

    # --- Instruction-tuned model ---
    print("\n--- Instruction-tuned model ---")
    prompt_inst = f"### Instruction:\n{q}\n### Input:\n\n### Response:\n"
    inputs_inst = tokenizer(prompt_inst, return_tensors="pt").to("cuda")
    outputs_inst = instruction_tuned_model_for_inference.generate(**inputs_inst, max_new_tokens=100)
    print(tokenizer.decode(outputs_inst[0], skip_special_tokens=True))
    print("="*80, "\n")

# Final cleanup of inference models
del base_model_for_inference
del instruction_tuned_model_for_inference
# del non_instruction_model # Keep this if it's meant to persist globally, otherwise uncomment to delete.
gc.collect()
torch.cuda.empty_cache()

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Tokenization + masking done.

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
Caching is incompatible with gradient checkpointing in LlamaDecoderLayer. Setting `past_key_values=None`.

Model Output (Instruction-tuned):

### Instruction:
 Detect duplication of land area values in the document.
### Input:

### Response:
* If the document contains duplicate land area values, an error will be returned to the caller.
* Otherwise, return 0 (success).

## Examples ##
### Example 1 ###
@Test
void test_DuplicateLandArea() throws Exception {
    LandArea lA = new LandArea();
    String docText = "\"This is a doc file.\"";
    long expected = 2; //expected number of lines

Question: Detect duplication of land area values in the document.

--- Non-instruction model (document-finetuned) ---
Detect duplication of land area values in the document.

















































































--- Instruction-tuned model ---
### Instruction:
Detect duplication of land area values in the document.
### Input:

### Response:

### Expected Output:

### Test Cases:

### Test Case 1:

### Test Case 2:

### Test Case 3:

### Test Case 4:

### Test Case 5:

### Test Case 6:

### Test Case 7:

### Test Case 8:

### Test Case 9:

###
================================================================================

Question: Identify inconsistencies in property market value information.

--- Non-instruction model (document-finetuned) ---
Identify inconsistencies in property market value information.

















































































--- Instruction-tuned model ---
### Instruction:
Identify inconsistencies in property market value information.
### Input:

### Response:

### Output:

### Expected Output:

### Test Cases:

### Test Case 1:

### Test Case 2:

### Test Case 3:

### Test Case 4:

### Test Case 5:

### Test Case 6:

### Test Case 7:

### Test Case 8:

### Test Case
================================================================================

Question: Find duplication in the document.

--- Non-instruction model (document-finetuned) ---
Find duplication in the document.

















































































--- Instruction-tuned model ---
### Instruction:
Find duplication in the document.
### Input:

### Response:

### Expected Output:

### Test Case 2:

### Input:

### Response:

### Expected Output:

### Test Case 3:

### Input:

### Response:

### Expected Output:

### Test Case 4:

### Input:

### Response:

### Expected Output:

### Test Case
================================================================================

First, ensure you have extracted the `merged_tinyllama_instruction.zip` file into your VSCode project directory. Let's assume you've placed it in a folder named `merged_tinyllama_instruction`.

Then, you can use the following Python code to load the model and tokenizer, and perform inference:

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import os

# Define the path to your saved merged model directory
# This path should be relative to where you run your Python script in VSCode
local_model_path = "./merged_tinyllama_instruction"

print(f"Loading model and tokenizer from: {local_model_path}")

# Check if the directory exists
if not os.path.exists(local_model_path):
    raise FileNotFoundError(f"Model directory not found at: {local_model_path}. "
                            "Please ensure you have unzipped 'merged_tinyllama_instruction.zip' "
                            "and placed the folder in the correct location.")

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(local_model_path)

# Load the fine-tuned model
# If your GPU has enough memory, you can try loading it to CUDA directly
# model = AutoModelForCausalLM.from_pretrained(local_model_path, torch_dtype=torch.float16).to("cuda")
model = AutoModelForCausalLM.from_pretrained(local_model_path)

# Ensure pad_token is set if not already in the tokenizer config (good practice)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Create a text generation pipeline
llm_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.float32, # Use torch.float16 if your GPU supports it and memory is a concern
    device=0 if torch.cuda.is_available() else -1 # Use GPU if available, else CPU
)

print("Model loaded and pipeline created successfully. Ready for inference!")

# Example inference with an instruction-tuned prompt
prompt = "### Instruction:\nIdentify inconsistencies in property market value information.\n### Input:\nProperty A: Value $500,000, Date 2023-01-01. Property A: Value $450,000, Date 2023-06-01.\n### Response:\n"

print(f"\nGenerating response for prompt:\n{prompt}")

outputs = llm_pipeline(
    prompt,
    max_new_tokens=100,
    num_return_sequences=1,
    do_sample=True,
    temperature=0.7,
    top_p=0.9,
    repetition_penalty=1.1
)

# Print the generated text
generated_text = outputs[0]["generated_text"]
print("\nGenerated Output:")
print(generated_text)

# You can integrate this into your application by calling the llm_pipeline with dynamic prompts.

In [ ]:
model="/content/llama-legal-domain"

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, BitsAndBytesConfig
from peft import PeftModel
import torch
import gc

# Ensure previous models are cleared from memory if they are no longer needed
if 'model' in globals():
    del model
if 'tokenizer' in globals():
    del tokenizer
if 'llm' in globals():
    del llm

gc.collect()
torch.cuda.empty_cache()

# Define the path to the saved LoRA adapters from the first fine-tuning step
LORA_ADAPTERS_PATH = "/content/llama-legal-domain"
ORIGINAL_MODEL_NAME = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"

# Load the tokenizer (from the original model)
tokenizer = AutoTokenizer.from_pretrained(ORIGINAL_MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Load the base model with quantization config
quantization_config = BitsAndBytesConfig(
    load_in_8bit=True
)

base_model_for_inference = AutoModelForCausalLM.from_pretrained(
    ORIGINAL_MODEL_NAME,
    quantization_config=quantization_config,
    device_map="auto"
)

# Load the LoRA adapters onto the base model
document_finetuned_lora_model = PeftModel.from_pretrained(
    base_model_for_inference,
    LORA_ADAPTERS_PATH
)

# Merge the LoRA adapters with the base model for inference
merged_document_finetuned_model = document_finetuned_lora_model.merge_and_unload()

# Create the text-generation pipeline
llm = pipeline("text-generation", model=merged_document_finetuned_model, tokenizer=tokenizer)

print("Document-finetuned model loaded and pipeline created successfully.")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/bnb.py:110: UserWarning: Merge lora module to 8-bit linear may get different generations due to rounding errors.
  warnings.warn(

Document-finetuned model loaded and pipeline created successfully.

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# Define the path to your saved merged model directory in your VSCode project
# Make sure this path is correct relative to where you run your script
local_model_path = "./my_finetuned_model_vscode" # Adjust this if you unzipped to a different location

print(f"Loading model and tokenizer from: {local_model_path}")

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(local_model_path)

# Load the fine-tuned model
# If your merged model was saved with a specific torch_dtype (e.g., float16), you might specify it here
model = AutoModelForCausalLM.from_pretrained(local_model_path)

# Ensure pad_token is set if not already in the tokenizer config (good practice)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Create a text generation pipeline
llm_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.float32, # Use torch.float16 if your GPU supports it and memory is a concern
    device=0 if torch.cuda.is_available() else -1 # Use GPU if available, else CPU
)

print("Model loaded and pipeline created successfully. Ready for inference!")

# Example inference with an instruction-tuned prompt
prompt = "### Instruction:\nIdentify inconsistencies in property market value information.\n### Input:\nProperty A: Value $500,000, Date 2023-01-01. Property A: Value $450,000, Date 2023-06-01.\n### Response:\n"

print(f"\nGenerating response for prompt:\n{prompt}")

outputs = llm_pipeline(
    prompt,
    max_new_tokens=100,
    num_return_sequences=1,
    do_sample=True,
    temperature=0.7,
    top_p=0.9,
    repetition_penalty=1.1
)

# Print the generated text
generated_text = outputs[0]["generated_text"]
print("\nGenerated Output:")
print(generated_text)

# You can integrate this into your application by calling the llm_pipeline with dynamic prompts.

Loading model and tokenizer from: ./my_finetuned_model_vscode

OSError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: './my_finetuned_model_vscode'.

In [ ]:
import os
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

# Define paths
ORIGINAL_MODEL_NAME = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
INSTRUCTION_ADAPTERS_PATH = "/content/tinyllama-instruction" # Path where instruction-tuned adapters were saved
OUTPUT_MERGED_MODEL_DIR = "/content/merged_tinyllama_instruction"

# Clear GPU memory (optional, but good practice)
gc.collect()
torch.cuda.empty_cache()

# Load the original base model to CPU first to avoid accelerate's device_map logic issues
# We remove device_map="auto" to prevent the TypeError.
base_model = AutoModelForCausalLM.from_pretrained(
    ORIGINAL_MODEL_NAME
)

# Load the instruction-tuned adapters onto the base model
instruction_tuned_model_for_merge = PeftModel.from_pretrained(
    base_model,
    INSTRUCTION_ADAPTERS_PATH
)

# Merge the LoRA adapters with the base model and unload them
merged_instruction_model = instruction_tuned_model_for_merge.merge_and_unload()

# Load the tokenizer (the one used during training)
tokenizer = AutoTokenizer.from_pretrained(ORIGINAL_MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Create the output directory if it doesn't exist
os.makedirs(OUTPUT_MERGED_MODEL_DIR, exist_ok=True)

# Save the merged model and tokenizer
merged_instruction_model.save_pretrained(OUTPUT_MERGED_MODEL_DIR)
tokenizer.save_pretrained(OUTPUT_MERGED_MODEL_DIR)

print(f"Merged instruction-tuned model and tokenizer saved to {OUTPUT_MERGED_MODEL_DIR}")

# Cleanup to free memory
del base_model
del instruction_tuned_model_for_merge
del merged_instruction_model
del tokenizer
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Merged instruction-tuned model and tokenizer saved to /content/merged_tinyllama_instruction

In [ ]:
import shutil
from google.colab import files

# Zip the directory containing the saved merged model and tokenizer
shutil.make_archive("merged_tinyllama_instruction", "zip", "/content/merged_tinyllama_instruction")

# Download the zipped file
files.download("merged_tinyllama_instruction.zip")

In [ ]:
import zipfile
import os
# Path to your zip file
zip_path = "/content/tinyllama-lora.zip"

# Extract all files
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall()